openapi: 3.0.0
info:
  title: Product-feedback
  description: Product-feedback app API
  version: 0.1.9

servers:
  - url: https://web-production-b206.up.railway.app/api
    description: production server
  - url: http://localhost:3000/api
    description: local server
paths:
  /feedbacks:
    get:
      tags:
        - Feedbacks
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /feedbacks/{id}:
    get:
      parameters:
        - in: path
          name: id
          schema:
            type: number
            example: 1
          required: true
      tags:
        - Feedbacks
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    delete:
      parameters:
        - in: path
          name: id
          schema:
            type: number
            example: 1
          required: true
      tags:
        - Feedbacks
      responses:
        "200":
          description: Feedback deleted
  /categories:
    get:
      tags:
        - Categories
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /status:
    get:
      tags:
        - Status
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /feedbacks/new:
    post:
      tags:
        - Feedbacks
      requestBody:
        description: create feedback
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                category_id:
                  type: number
            example:
              title: Node is awesome
              description: Don't use nodemon on server
              category_id: 2
      responses:
        "200":
          description: feedback created
  /users:
    get:
      tags:
        - Users
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /comments:
    post:
      tags:
        - Comments
      requestBody:
        description: create comment
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: object
                feedbackId:
                  type: number
                userId:
                  type: number
            example:
              content: Awesome idea! Trying to find framework-specific project within hubs can be tedious
              feedbackId: 1
              userId: 2
      responses:
        "200":
          description: comment created
